name: "CI"
on: # rebuild any PRs and main branch changes
  pull_request:
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!

      # we may use whatever way to install phpcs, just specify the path on the next step
      # however, curl seems to be the fastest
      - name: Install PHP_CodeSniffer
        run: |
          composer global require "squizlabs/php_codesniffer=*"
          ./vendor/bin/phpcs -h
          phpcs -i
          php phpcs.phar --version
      - uses: tinovyatkin/action-php-codesniffer@v1
        with:
          files: "wp-includes/ebay/**.php"
          phpcs_path: php phpcs.phar
          standard: PSR2
